### ISSUE TITLE
time-varying coefficient in Fine-Gray regression competing risk models

### ISSUE THREAD

**Issue by i2sunshine** [tagteam/riskRegression#11]
Hello! How to use your command FGR to replicate results by below command crr from Package "cmprsk"? In below case, effect (logHR) of X1 = a + t*b, where a is the effect at time 0.

#library(prodlim)
#library(survival)
#library(cmprsk)
#library(lava)

d <- prodlim::SimCompRisk(100)
crr.fit=crr(d$time, d$cause, cov1=d[, c("X1", "X2")], cov2=d$X1, tf=function(t) t, failcode=1, cencode=0)

Thank you!
Regards,
Jessie

**Comment by tagteam** [comment]
you need to copy the X1 variable in order to use it both with and without time-varying effect, like this:

library(riskRegression)
library(cmprsk)
library(prodlim)
set.seed(9)
d <- prodlim::SimCompRisk(100)
crr.fit=crr(d$time, d$cause, cov1=d[, c("X1", "X2")], cov2=d$X1, tf=function(t) t, failcode=1, cencode=0)
idfun <- function(x){x}
d$copyX1 <- d$X1
fgr.fit <- FGR(Hist(time,cause)~cov2(copyX1,idfun)+X1+X2,data=d,cause=1)
fgr.fit$crrFit
crr.fit

ps: it is Fine-Gray not Fine-Grey

**Comment by i2sunshine** [comment]
I get it. Thanks a lot!
